-- Tạo cơ sở dữ liệu tên TRUONGHOC
CREATE DATABASE IF NOT EXISTS TRUONGHOC;
-- sử dụng cơ sở dữ liệu
USE TRUONGHOC;
-- Câu lệnh SQL để tạo các bảng
DROP TABLE IF EXISTS TRUONG;
DROP TABLE IF EXISTS PHONG_GD_DT;
DROP TABLE IF EXISTS SO_GD_DT;
DROP TABLE IF EXISTS LOAIHINH;
DROP TABLE IF EXISTS LOAITRUONG;
CREATE TABLE LOAITRUONG(
	MA_LOAI_TRUONG char(1) PRIMARY KEY,
	TEN_LOAI_TRUONG varchar(100));

CREATE TABLE LOAIHINH(
	MA_LOAI_HINH char(1) PRIMARY KEY,
	TEN_LOAI_HINH varchar(20) NOT NULL);

CREATE TABLE SO_GD_DT(
	MA_SO char(1) PRIMARY KEY,
	TEN_SO varchar(50) NOT NULL);

CREATE TABLE PHONG_GD_DT(
	MA_PHONG char(3) PRIMARY KEY,
	TEN_PHONG varchar(60) NOT NULL,
	MA_SO char(2) NOT NULL,
	CONSTRAINT foreign key (MA_SO) references SO_GD_DT(MA_SO));

CREATE TABLE TRUONG(
	MATRUONG varchar(11) PRIMARY KEY,
	TENTRUONG varchar(100) NOT NULL,
	MASO char(1) NOT NULL,
	MAPHONG char(3),
	DIACHI varchar(100),
	MA_LOAI_HINH char(1),
	MA_LOAI_TRUONG char(1),
	CONSTRAINT foreign key (MASO) references SO_GD_DT(MA_SO),
	CONSTRAINT foreign key (MAPHONG) references PHONG_GD_DT(MA_PHONG),
	CONSTRAINT foreign key (MA_LOAI_HINH) references LOAIHINH(MA_LOAI_HINH),
	CONSTRAINT foreign key (MA_LOAI_TRUONG) references LOAITRUONG(MA_LOAI_TRUONG));
